# Generated by Django 5.0.6 on 2024-06-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signup",
            name="id",
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
