# Generated by Django 5.0.6 on 2024-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_authentication", "0002_remove_signup_id_alter_signup_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=150)),
                ("message", models.TextField(max_length=280)),
            ],
        ),
    ]
